#! /bin/sh

#  This script is here only for the Codehaus Bamboo build.  The script has to know that the build actually
#  executes in .. not . and that this directory is ../checkout.
#
#  Use the -i option on grdlew so that the log has extra information in by default.

cd checkout

./gradlew -i clean build
