#! /bin/sh

#  This script is here only for the Codehaus Bamboo RELEASE build.

buildTask="release"

if [ $# -gt 0 ]
then
    buildTask=$1
fi

export LC_ALL=en_GB.UTF-8

./gradlew -i clean $buildTask
